services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="mongodb+srv://loprommy55:1234@khan.hoqrd.mongodb.net/nvc_cake"
      - JWT_SECRET="euwQ5uyxfIdf02Zh7BE"
      - PORT=3001
    networks:
      - caddy
  app-migrate-deploy:
    build:
      context: .  
      dockerfile: Dockerfile
      target: builder
    command: bun x prisma migrate deploy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="mongodb+srv://loprommy55:1234@khan.hoqrd.mongodb.net/nvc_cake"
      - JWT_SECRET="euwQ5uyxfIdf02Zh7BE"
      - PORT=3001
    networks:
      - caddy

networks:
  caddy:
    external: true
